- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.15.0'
  hooks:
  -   id: mypy
      # 排除某些文件
      # exclude: ^(docs/|legacy/|migrations/).*\.py$
        
      # pre-commit 特定的配置
      # files: ^(src/new_features/|tests/new_features/).*\.py$

      # 使用 setup.cfg 中的 mypy 配置 
      # 可以组合多个参数
      args: [
          "--config-file=setup.cfg",
          "--python-version=3.11",
          "--show-error-codes",
      ]

